wallpaper {
    monitor = DP-1
    path = /home/netsu/bin/wallpapers/1744323197451806.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/netsu/bin/wallpapers/1651452009708.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/netsu/bin/wallpapers/1719587638699426.jpg
    fit_mode = cover
}

splash = false