wallpaper {
    monitor = HDMI-A-1
    path = /home/netsu/wallpapers/1753136950150246.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/netsu/wallpapers/1633080884422.png
    fit_mode = cover
}

splash = false